### ISSUE TITLE
Feature request: switch between options API and composition API in code blocks.

### ISSUE THREAD

**Issue by HendrikJan** [vuejs/docs#1143]
Currently, most of the code blocks in the documentation show code for the options API. (with the exception of the item "Composition API" of course).
I am trying to use the composition API, and I find it difficult to translate the options API examples to composition API code.

It would be usefull if every code block in the documentation contained a button to switch between composition API and options API.

I understand that this might be a huge undertaking while resources are limited, but it might be worth the work.
* This change would clearly communicate to new users that there are two apis.
* Even if you don't really understand the difference between the API's, when using the button to switch, you would easily see which code fits with the other code that you are already using.

(Ideally there would also be a switcher button for Javascript and Typescript.)

**Comment by skirtles-code** [comment]
As I noted on #1139, the addition of the composition API does pose a documentation challenge.

Could you provide some examples of specific code samples that you think would benefit from this? I'd like to get a better sense of the problem. There might be other ways to approach this.

**Comment by HendrikJan** [comment]
@skirtles-code I can understand that the composition API poses a challenge and I am thankful of all the work done.
Please see this as a suggestion for one possible approach.

In my opinion this would be added to all code examples in the documentation, as you don't know the experience level of the visitor.
It might look like this:
![image](https://user-images.githubusercontent.com/2218920/126862635-b8e9f078-a7c9-4584-8645-639d40c11a3c.png)
The button bar would only appear when hovering the code examples.

I understand that the above picture would require 2x2x2 versions of the example-code and may be too much to maintain.
Only a switch between composition API and options API would already be great.

**Comment by HendrikJan** [comment]
@skirtles-code as a direct response to your question:

The page about [Instance Lifecycle Hooks](https://vuejs.org/v2/guide/instance.html#Instance-Lifecycle-Hooks) has code examples that are difficult to read if you try to build your Vue project using the composition API.
Instead of a button, in this case a message stating "for using hooks in the composition API look here" might already be an improvement.

In my case I was further confused because I am building a Nuxt application, and Nuxt requires a different approach for some parts of the code as well.
In the end I decided to go for the options-API, as that requires less code and is more readable to myself and my colleagues.

Thank you for your time.

**Comment by skirtles-code** [comment]
@HendrikJan The Vue 2 docs have a separate repo: https://github.com/vuejs/vuejs.org/issues.

The situation for Vue 2 is a little different because the Composition API is included via a separate library and is not yet part of Vue itself. That should change in Vue 2.7. I don't work on the Vue 2 documentation myself but I would imagine that it will be updated to include material about the Composition API when 2.7 is released. I expect it'll be similar to what is in the Vue 3 documentation.

As for Vue 3...

The main guides are written assuming the reader has no prior knowledge of Vue whatsoever. We do make some assumptions about other knowledge, as stated early in the Introduction:

> The official guide assumes intermediate level knowledge of HTML, CSS, and JavaScript.

The guides are intended to be read in order, starting from zero knowledge of Vue. At each stage we try to ensure that we don't lean on concepts that haven't been introduced previously. When we can't avoid that we directly acknowledge that something hasn't been discussed yet.

We also need to avoid overwhelming readers early on in the guides. Discussing SFCs or the Composition API too early could appear daunting and scare people away. We are hoping to introduce SFCs a little earlier than we do currently but it still wouldn't be until after the Essentials section.

With all that in mind, having some form of button for toggling between CDN, ESM and/or SFC versions of the code is an idea that's been bouncing around for a while. The use of a global/CDN build in all the early guide examples can cause confusion for readers who are using ES modules and aren't familiar with how to switch between the two styles.

Likewise, a way to toggle between JS and TS is potentially useful and is unlikely to cause much confusion. There are some technical difficulties with implementing something like that but that should become easier in the coming months.

Toggling between the Options API and Composition API is more problematic. The code examples have to make sense in the context of the surrounding text explaining them. They also have to fit within the wider narrative of the guides, which need to introduce concepts one at a time. That makes it difficult for most of the code samples to switch between the two APIs. The code might still achieve the same end result but it wouldn't demonstrate the topic being taught. Take this page for example: https://v3.vuejs.org/guide/data-methods.html. It is specifically trying to teach readers about `data` and `methods`. The code samples have to reflect that, the explanations wouldn't make sense if the code were using the Composition API instead.

The API Reference portion of the documentation is slightly different. That isn't intended to be read in order and it can freely reference other parts of Vue wherever they're appropriate. There's definite room for improvement there. For example, the sections about using lifecycle hooks and `provide`/`inject` with the Options API don't currently mention the Composition API at all. At a minimum there should be links between the equivalent concepts in the two API styles.

**Comment by HendrikJan** [comment]
@skirtles-code thank you!

Knowing that there is a Vue 2 and a Vue 3 version of the documentation helps me a lot.
The Vue 3 documentation looks very good already.
