### ISSUE TITLE
Recommend Volar on the IDE Support section

### ISSUE THREAD

**Issue by ahsan-a** [vuejs/docs#1206]
I've found [Volar](https://marketplace.visualstudio.com/items?itemName=johnsoncodehk.volar) to be a lot better than vetur, especially with typescript support. I think It deserves to be listed on the [IDE Support Page](https://v3.vuejs.org/guide/migration/introduction.html#ide-support) so more people can find it.

**Comment by skirtles-code** [comment]
I believe this is an oversight. Elsewhere the docs were recently switched to recommending Volar:

* https://v3.vuejs.org/guide/typescript-support.html#editor-support
* https://v3.vuejs.org/api/sfc-tooling.html#ide-support

**Comment by ahsan-a** [comment]
ahh, i must have missed that. Do you reckon it would still be a good idea to recommend volar alongside vetur? I haven’t yet came across something vetur can do that volar can’t do.

**Comment by skirtles-code** [comment]
Sorry, I may not have been clear. I believe the current reference to Vetur is incorrect and it should be changed to Volar, the same as the other places that make IDE recommendations.

Personally I don't use VSCode, so it is possible that I'm missing something, but I'm not aware of any circumstances where Vetur should be recommended instead of Volar.

**Comment by NataliaTepluhina** [comment]
Thank you for reporting this! Changed Vetur to Volar 👍🏻
