### ISSUE TITLE
Clarify V3 Migration strategy for TS Vue.extend (#2)

### ISSUE THREAD

**Issue by lukashroch** [vuejs/docs#1502]
Sorry for re-opening, but how does this apply for single components & vue3? This is OK for augmenting the global vue (which is already in vue2), but not for per-component case in vue3. The original example is for vue2 & single component.

https://vuejs.org/api/utility-types.html#componentcustomproperties

_Originally posted by @yyx990803 in https://github.com/vuejs/docs/issues/1446#issuecomment-1032117808_

**Comment by leopiccionia** [comment]
I don't know the position of Vue team, but, as a user, if I aimed for optimal TypeScript support:

* instead of local mixins, I'd use the Composition API — it was originally created for composition-over-inheritance scenarios like this;
* instead of `this.$refs`, I'd use Composition API's typed template refs for [HTML elements](https://vuejs.org/guide/typescript/composition-api.html#typing-template-refs) and [Vue components](https://vuejs.org/guide/typescript/composition-api.html#typing-component-template-refs).

**Comment by lukashroch** [comment]
I get that you can use for all of that composition API. We indeed want to use that in future. But for large codebases, that's not an easy path to rewrite suddenly everything in one go using composition API.

Especially if it was supported in Vue2 and as I understand Vue3 still fully supports Options API. So I'm hoping Typescript support for Options API can also kept in place. Otherwise it juts got crippled for TS users ... keeping Options API in place with removed TS support. So vue2 TS users will be forced to rewrite all at once or nothing.

**Comment by leopiccionia** [comment]
You don't need to "rewrite suddenly everything in one go".

Composition API can be used [inside Options API](https://vuejs.org/guide/reusability/composables.html#using-composables-in-options-api).

You can migrate mixin by mixin, consumer by consumer, often without having to touch the rest of the component (if the mixins didn't have implicit dependencies in non-mixin code).

But, yes, I don't know if there's an easy and type-safe migration path for TypeScript users that want to keep using local mixins.

**Comment by lukashroch** [comment]
Let's assume vue2 is swapped to vue3 and we deal with local mixins in local components (!no global vue instance augmentation!).

- you have large code base written in vue2 & TS, so most of the components are probably using Vue.extend
- syntax `export default (Vue as VueConstructor<Vue & InstanceType<typeof someMixin & whateverOtherTypesThatAreNotResolvedAutomatically...>).extend({...}` is gone -> no longer in V3. 
- so you swap to `defineComponent`, which resolves `setup()`  but not mixins etc...
- your typings from `Vue.extend` are gone
- Options API still works for JS ... but not for TS anymore

Am I missing something how you can do this gradually without rewriting everything in one go if TS relied on Vue.extend? Happy to be guided here, really :-)

**Comment by lukashroch** [comment]
Resolves to unknown for me, even if all defined with `defineComponent`, but that's only just the mixins...

**Comment by LinusBorg** [comment]
So let's approach this gradually and identify how far we can get:

Concerning a gradual approach, you could use the Vue 2 composition API plugin to be able to use `defineComponent()` in Vue 2 already, making it possible to switch your components over one by one before moving on to Vue 3.

1. Mixins do indeed work with `defineComponent()`: 

<img width="411" alt="Bildschirmfoto 2022-02-09 um 19 40 20" src="https://user-images.githubusercontent.com/1444526/153267988-4c9e01eb-b77b-4e57-a125-5c35fae93140.png">

2. `$refs` should be not too common throughout a codebase (unless it relies on tons of jquery stuff, and if so, can be typecast in place without too much hassle. Another alternative would be to use template refs with setup as a gradual migration strategy:

```
export default defineComponent({
  setup() {
    const someComponent = ref<typeof SomeComponent>()

    return {
      someComponent
    }
  },
  // rest of the component in Options API, 
  // replacing `this.$refs.someComponent` with `this.someComponent`
})
```

3. The only sticking point would be Vuex. It's use is likely common throughout your codebase and notoriously hard to type. I don't see a nice way to migrate that right now. To be honest, pretty much all Vue 2 Codebases that use Vuex which I came across used some sort of 3rd party wrapper. Your approach wasn't even on our, or at least my, radar.

**Comment by lukashroch** [comment]
Thanks, already using composition plugin and trying to have new work vue3 forward compatible. Though these are approaches how to do the rewrites to composition API, not to keep types for existing Options API which is still supported, but weirdly types are not.

But my point is that once vue2 to vue3 is swapped, `Vue.extend` used for TS is gone, while `Options API` is still there... So nothing gradual about that. So by that time you want to swap, you have to have everything rewritten or stick with vue2 + composition plugin and also lagging with other 3rd party upgrades.

I was more wondering if they could be provided through `defineComponent` generics or something similar.

**Comment by LinusBorg** [comment]
@pikax do you have any bright ideas on how we could enable that?

**Comment by pikax** [comment]
> @pikax do you have any bright ideas on how we could enable that?

@LinusBorg maybe providing an `Vue.extend`  on `@vue/compat`, basically `defineComponent` but with a different name.

--- 

Vue3 provides superior typescript support than vue2, with full support for Options API. 

@lukashroch do you mind providing a concrete example of what is not supported? Composition-API is preferred instead of Mixins going forward. 

Before I misunderstand your question do you mind explaining (ideally with a repo code/link) what you cannot achieve in vue3 but you're able to do it on vue2? 


--- 




> * you have large code base written in vue2 & TS, so most of the components are probably using Vue.extend

Personally I would find&replace, replacing `Vue.extend` with `defineComponent`. Easiest solution, you could make it more complex, but I don't think is worth it.



> * syntax `export default (Vue as VueConstructor<Vue & InstanceType<typeof someMixin & whateverOtherTypesThatAreNotResolvedAutomatically...>).extend({...}` is gone -> no longer in V3.

Do you mind explaining a bit better? That is something that I would try to avoid, if you need mixins, just import them in the component. 

```ts
defineComponent({
 mixins: [ someMixin ]
 // ....
})
```

> * so you swap to `defineComponent`, which resolves `setup()`  but not mixins etc...

Not sure what you mean here, if the `mixins` are not working, that's a bug and should be fixed, can you provide an example?



> * your typings from `Vue.extend` are gone

They are replaced with the `defineComponent` and [Utility Types](https://vuejs.org/api/utility-types.html)




> * Options API still works for JS ... but not for TS anymore

This should work in vue3 for sure! Can you provide an example?

**Comment by LinusBorg** [comment]
@pikax let me try and give you a quick recap of the problem:

As we know in Vue 2 Options API, there are a bunch of things that are not straightforward to get type inference for when usign `Vue.extend()` which is the default approach to get some level oft ype hints. Among these are:

* properties from mixins
* $refs
* Properties from Vuex

OP found a way that works for them by extending the `VueConstructor<>` type in the way they shared above, essentially typecasting those properties that were not inferrable /annotatable by Vue automatically onto the current components `this` .

But that way is not replicable in Vue 3's `defineComponent()` as there is no such generic to extend, so they are worried that a migration to Vue 3 would mean that they had to fundamentally rewrite all their components at once in composition API or something as otherwise all these types break.

So the main question is: is there a way to extend an individual component's `this` type (public instance) with arbitrary interfaces similar to what OP did? And extending from that, is there a way to achieve that with `defineComponent()` in the Vue 2 plugin, which in my quick experiment at least, was not able to infer mixin types the way Vue 3's was able to?

**Comment by pikax** [comment]
Thanks @LinusBorg that helped me understanding the issues OP is facing.

**Comment by pikax** [comment]
Thank you @LinusBorg 

Now I understand the issue that OP is facing. 

Extending `this` type on `defineComponent` is not possible (at the least without major hacks), this is because we already override the `this` on the `defineComponent` argument, Vue3 does not support `extend` API (only with compat, but there's no typings there). 




> * properties from mixins
> * $refs
> * Properties from Vuex

- `properties from mixins` this should work when using `mixin` or `extend`, no type override should be required.

- `$refs` not supported to define `$refs`, simply we cannot support this because there's no way to declare it, also the advantages this will bring are not many, the recommended way to do this is by using [setup](https://v3.vuejs.org/guide/composition-api-template-refs.html#template-refs) which will be type safe - https://github.com/vuejs/core/pull/5387

- `Properties from Vuex` this is hit-and-miss, if using pure vuex (no third-party libs), you can achieve a similar behaviour by casting your `map*` functions
```ts
declare function mapGetters(o: any): any

defineComponent({
  computed: {
    // NOTE we need to cast it to be a function, just like a computed is a function
    ...(mapGetters(['foo', 'bar']) as { foo: ()=> number; bar: ()=>string })
  },

  methods: {
    test(){
      this.foo.toExponential()

      // @ts-expect-error
      this.bar = this.foo
    }
  }
})
```

**Comment by pikax** [comment]
> The issue is that Options API & TS works with `defineComponent`, but only if you convert everything. I don't think you can mix & match `defineComponent` and `Vue.extend` with injected types like in the example. So you got to jump the boat, find and replace everything with defineComponent...

That's correct, they won't work together well. My recommendation is moving everything to `defineComponent`, it might be tedious and a lot of work, but supporting a direct cast is not reasonable IMO. 


If you migrating, the first thing is to check the [migration](https://v3-migration.vuejs.org/migration-build.html#installation), after you are using vue3 (without typechecking yet), the next step is to replace the `Vue.extend` with `defineComponent`, I **would not** add or changing javascript code on those components, only tweaking Typescript, the first few components will be tricky to figure out how to do it, but you will find a pattern within your codebase. 




> * $refs - relatively easy to do if you don't have too much logic around them, then you start to rewiring the component itself

If having typed `$refs` is a must, I would cast them inline or using a `computed`. I would not add a `setup` just for that.


> * local callbacks in `created`, like debounce or something... again, can convert with `setup`, but if logic is in data() etc, you start to rewiring the component and rewriting to composition API

Lifecycle are a bit tricker to alter, but you can do something [like this](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHNjcmlwdD5cbmltcG9ydCB7IGRlZmluZUNvbXBvbmVudCB9IGZyb20gJ3Z1ZSdcbiAgXG4vL2h0dHBzOi8vZGF2aWR3YWxzaC5uYW1lL2phdmFzY3JpcHQtZGVib3VuY2UtZnVuY3Rpb25cbmZ1bmN0aW9uIGRlYm91bmNlKGZ1bmMsIHdhaXQsIGltbWVkaWF0ZSkge1xuXHR2YXIgdGltZW91dDtcblx0cmV0dXJuIGZ1bmN0aW9uKCkge1xuXHRcdHZhciBjb250ZXh0ID0gdGhpcywgYXJncyA9IGFyZ3VtZW50cztcblx0XHR2YXIgbGF0ZXIgPSBmdW5jdGlvbigpIHtcblx0XHRcdHRpbWVvdXQgPSBudWxsO1xuXHRcdFx0aWYgKCFpbW1lZGlhdGUpIGZ1bmMuYXBwbHkoY29udGV4dCwgYXJncyk7XG5cdFx0fTtcblx0XHR2YXIgY2FsbE5vdyA9IGltbWVkaWF0ZSAmJiAhdGltZW91dDtcblx0XHRjbGVhclRpbWVvdXQodGltZW91dCk7XG5cdFx0dGltZW91dCA9IHNldFRpbWVvdXQobGF0ZXIsIHdhaXQpO1xuXHRcdGlmIChjYWxsTm93KSBmdW5jLmFwcGx5KGNvbnRleHQsIGFyZ3MpO1xuXHR9O1xufTtcblxuZXhwb3J0IGRlZmF1bHQgZGVmaW5lQ29tcG9uZW50KHtcblx0ZGF0YSgpe1xuICAgICByZXR1cm4geyBtc2c6ICdIZWxsbyB0aGVyZSd9IFxuXHR9LFxuIFxuICAvLyBiZWZvcmVDcmVhdGUgaXMgcmVuZGVyIGJlZm9yZSBvcHRpb25zIEFQSTogaHR0cHM6Ly92dWVqcy5vcmcvZ3VpZGUvZXNzZW50aWFscy9saWZlY3ljbGUuaHRtbCNsaWZlY3ljbGUtZGlhZ3JhbVxuICBiZWZvcmVDcmVhdGUoKXtcbiAgICB0aGlzLiQudHlwZS5tb3VudGVkID0gZGVib3VuY2UodGhpcy4kLnR5cGUubW91bnRlZCwgMTAwMClcbiAgfSxcbiAgXG4gIG1vdW50ZWQoKXtcblx0XHR0aGlzLm1zZyA9ICdHZW5lcmFsIEtlbm9iaSdcblx0fVxuXG59KVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGgxPnt7IG1zZyB9fTwvaDE+XG4gIDxpbnB1dCB2LW1vZGVsPVwibXNnXCI+XG48L3RlbXBsYXRlPiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcbiAgICBcInZ1ZVwiOiBcImh0dHBzOi8vc2ZjLnZ1ZWpzLm9yZy92dWUucnVudGltZS5lc20tYnJvd3Nlci5qc1wiXG4gIH1cbn0ifQ==) (I don't recommend that, but it might be an option), there's no need to use `setup` at all in most of the cases. 



> * mixin merging strategy issues - `data()` and `setup()` are resolved in different time and `setup()` does not have this. So if mixins  / components rely on merging strategy and you move one mixin to `setup()` you break it since setup() resolve it before data and later mixin overwrites

I guess you won't have this issue if you don't port to `setup` on phase1, you can gradually deprecate `mixins` while you converting them to composition API (if that's the goal)






> Each of these can be resolved and will be better once it's done in composition API, I'm not arguing about that. But the problem is that if you take the `Vue.extend` out, you have resolve these all at once.

Direct casting always comes back to bit you, I can provide help on particular scenarios and how to possibly type them correctly, each codebase is different.

**Comment by lukashroch** [comment]
@pikax, @LinusBorg thank you, really helpful to have these answers!

Does the TS inference work for `defineComponent` in composition plugin or only in vue3? I already use composition plugin for newer code, but not yet with mixins inference. So just did a quick test and it resolves to unknown. Am I missing something?
![Screenshot 2022-02-10 134411](https://user-images.githubusercontent.com/223967/153420231-dc770d2c-fb80-45e3-b5de-a03a8492d909.png)

**Comment by pikax** [comment]
@lukashroch yes only on Vue3

**Comment by lukashroch** [comment]
@pikax thanks for confirming!
