### ISSUE TITLE
Redirect https://vuejs.org/v2 to https://v2.vuejs.org/v2

### ISSUE THREAD

**Issue by tony19** [vuejs/docs#1779]
The previously working links to Vue 2 docs now point to Vue 3 docs, but the new page usually does not contain the original content, so the page isn't as helpful.

For instance, the first link below was intended for a Vue 2 page about annotating props in TypeScript, but it lands on a page about using TypeScript in Vue 3 and no mention of props.

https://vuejs.org/v2/guide/typescript.html#Annotating-Props
versus:
https://v2.vuejs.org/v2/guide/typescript.html#Annotating-Props (intended page)

I think it would be helpful to redirect https://vuejs.org/v2/ to https://v2.vuejs.org/v2/ so that the original links work again (perhaps via [Netlify config](https://docs.netlify.com/routing/redirects/)).

**Comment by yyx990803** [comment]
This is intentional. The main reason is that most Vue related search results on Google points to these v2 URLs, and it would be confusing to land on v2 docs now that Vue 3 is the default version.

Also, we actually did what you proposed for 3 months (after v3 docs launch), with a notice suggesting anyone landing on v2 URLs to start using `v2.vuejs.org` instead, before redirecting v2 URLs to v3. It is our hope that most users who rely on v2 docs should have seen that notice by now.

**Comment by tony19** [comment]
Ok, I see. My main concern was old links on Stack Overflow. There's about 3k posts that contains the old URL, and those links should still point to their original Vue 2 docs in order for the Vue 2-specific posts to make sense. I'll probably write a script to automatically update the URLs in those posts in Stack Overflow.

**Comment by tony19** [comment]
FYI, I've updated all old links in Stack Overflow posts to use https://v2.vuejs.org/v2.
