### ISSUE TITLE
Feature: Copy code snippets to clipboard

### ISSUE THREAD

**Issue by hichemfantar** [vuejs/docs#1789]
Could we possibly get this functionality?

**Comment by kiaking** [comment]
The feature is implemented in latest VitePress. Because the theme system is different it's not about just upgrading VitePress but I'm planning to bring many features into Vue website theme from VitePress.

Don't have estimated timeline when that might happen, but I'm hoping to do this sometime this year 👀

**Comment by hichemfantar** [comment]
@kiaking Alright, sounds good. Appreciate your work on the project btw 👏

**Comment by Gautam-Arora24** [comment]
Hey! Can I work on this issue?

**Comment by skirtles-code** [comment]
This should now be implemented following the latest theme updates.
