### ISSUE TITLE
Navbar on top of Vue mastery banner on mobile

### ISSUE THREAD

**Issue by hichemfantar** [vuejs/docs#1846]
Only happens when I scroll 
![Screenshot_20220721-115512.jpg](https://user-images.githubusercontent.com/34947993/180197791-83462e01-9f2b-4c83-ae18-b449de378a38.jpg)

**Comment by xfq** [comment]
It's probably because the [z-order](https://github.com/vuejs/vitepress/blob/70125e7b912d36670e143d5b454875e8c3a3f52f/src/client/theme-default/styles/vars.css#L172) of the [VPNav](https://github.com/vuejs/vitepress/blob/70125e7b912d36670e143d5b454875e8c3a3f52f/src/client/theme-default/components/VPNav.vue#L34) component is larger than the Vue Mastery banner.

**Comment by hichemfantar** [comment]
Will attempt a PR.

**Comment by xfq** [comment]
FYI - the banner component is in https://github.com/vuejs/docs/blob/main/.vitepress/theme/components/VueMasteryBanner.vue

**Comment by hichemfantar** [comment]
This pr should fix it.
