### ISSUE TITLE
Space around docs center column would improve readability

### ISSUE THREAD

**Issue by aldencolerain** [vuejs/docs#2014]
The current Vue3 documentation feels cramped and hard to read.  I think adding space, even a small amount, between the central column and left/right columns would greatly increase readability.  Alternatively shifting the left and right columns to the edges of the screen like Vue2 docs would help even more.  As a reference point, Firefox has a build in "reader view" that is designed to ease readability and it essentially does this exact transformation. 

Current docs that to me feel hard to read:
![image](https://user-images.githubusercontent.com/16270737/195770977-214c37a3-9023-4457-a172-e542f98a9f06.png)

Proposal to improve readability:
![image](https://user-images.githubusercontent.com/16270737/195771153-d89dc607-2f40-4d3b-848b-b41a7a92edac.png)

**Comment by kiaking** [comment]
Thanks for the feedback! As a reference point, we have quite large spacing (96px) on left/right side of the content, and for the docs site where the sidebar is not fixed to the left of the window out there, I assume we have the largest spacing for example compared to TailwindCSS doc (where they have 64px).

I understand your preference, but for me, having a sidebar menu and outline close to the content is easier to navigate.

It's not that your opinion is wrong, but this is a hard one because not everyone thinks the same way.

Let's keep this issue open for few more days and see if we can get any feedback from community.

**Comment by kiaking** [comment]
Closing the issue for now. Maybe Redis docs has less elements on both sidebar and right side items so that matters too 🤔

Feel free to open another issue if you find anything!
