### ISSUE TITLE
possibly incomplete/incorrect statement about loss of reactivity due to destructuring

### ISSUE THREAD

**Issue by JeraldVin** [vuejs/docs#2101]
from Vue docs https://vuejs.org/guide/essentials/reactivity-fundamentals.html#limitations-of-reactive and https://vuejs.org/api/composition-api-setup.html#accessing-props

> It also means that when we assign or destructure a reactive object's property into local variables, or when we pass that property into a function, we will lose the reactivity connection:

> Note that if you destructure the props object, the destructured variables will lose reactivity. It is therefore recommended to always access props in the form of props.xxx. If you really need to destructure the props, or need to pass a prop into an external function while retaining reactivity, you can do so with the [toRefs()](https://vuejs.org/api/reactivity-utilities.html#torefs) and [toRef()](https://vuejs.org/api/reactivity-utilities.html#toref) utility APIs:

However, this _loss of reactivity_ limitation seems to be occurring only for **primitive props** and **primitive properties of the reactive object**. The reactivity is preserved for objects/arrays(component gets updated, able to trigger watch(), etc). Repo to reproduce this -> https://github.com/JeraldVin/vue-prop-destructure - have attached screenshot of the app

So, do the above statements in the docs need to be updated?

Also, vue's eslint plugin has this rule -> vue/no-setup-props-destructure . Does this rule also need to be updated(for object/array props)?

<img width="1512" alt="Screenshot 2022-11-20 at 5 14 32 PM" src="https://user-images.githubusercontent.com/46400789/202901033-ac441f8c-57d4-4c46-90dd-8ad27ffbab54.png">

**Comment by LinusBorg** [comment]
Heres the thing: When the docs say "the destructured variables lose reactivity", that means: those new variables' values themselves won't magically update when the properties of `props` from which they were destructured were changed - which is to say: when the props changed. (That's not so much because of reactivity but because of JS itself, see below).

But if the value of a prop is itself a reactive object, *that object's properties* will of course still be reactive. it's just when the parent would pass a *new* reactive object to a prop, then *that new prop value* will not be reflected in the destructured variable.

The loss of reactivity when destructuring props is rooted in what plain JS itself does when destructuring:

```js
const { someprop } = someObject

// is functionally equivalent to:
const somePropVar = someObject.someProp

someObject.someProp = 'a new string' // somePropVar will still be the previous value
someObject.someProp = { a: 'new object' } // somePropVar will still be the previous value
```

So maybe we need to stress this native JS foundation more than the "loss of reactivity"?

**Comment by JeraldVin** [comment]
thanks for your time and comment, @LinusBorg


> So maybe we need to stress this plain JS principle more than the "loss of reactivity"?

So do you suggest to close this issue or keep it open?
