### ISSUE TITLE
组件基础 -- 定义一个组件章节中“当使用构建步骤时....” "When using a build step" 是什么意思？

### ISSUE THREAD

**Issue by hm20062006ok** [vuejs/docs#2327]
中文，英文我都没看懂这句话的意思

**Comment by skirtles-code** [comment]
I believe this issue is referencing this part of the docs, <https://vuejs.org/guide/essentials/component-basics.html#defining-a-component>. Specifically:

> ### Defining a Component
>
> When using a build step, we typically define each Vue component in a dedicated file using the `.vue` extension

I can't really comment on the Chinese translation, but we probably could make that a little clearer in the English version. The phrase 'When using a build step' is referring to applications that use build tools like Vite or webpack, but I can see how the intended meaning of that phrase would not be obvious.

The phrase 'build step' is used earlier in the docs, e.g. in <https://vuejs.org/guide/quick-start.html>. I think its use there is less confusing given the context.

**Comment by yyx990803** [comment]
组件这一章节默认了你已经阅读了之前的章节，同时也默认了在学习框架前你应该具备基本的前端基础知识。如果你对于前端 “构建” 的概念完全不了解，你可能需要补充一些相关的背景知识再来学习框架。
