### ISSUE TITLE
Inappropriate translation in sections of interactive tutorial in Chinese version 

### ISSUE THREAD

**Issue by Hsin-Lan** [vuejs/docs#2695]
Hello Team,

I found some inappropriate translations in Chinese version of sections of interactive tutorial parts. 

For example, for section 11 component, in Chinese the tutorial mentions the parent component as "father component" and the child component as "son component" which I think blocking the gender equality in the area of programming.

Thank you,
Hsin
<img width="628" alt="Screen Shot 2024-02-12 at 00 46 57" src="https://github.com/vuejs/docs/assets/115072608/6464b8ba-faf9-4a5d-a7d1-582c22d5bdb7">

**Comment by brc-dd** [comment]
Hi, please create this issue at the translation repository - https://github.com/vuejs-translations/docs-zh-cn

I believe the English version uses gender-neutral nouns for most of the text. But sometimes there might be occurrences that people might not find appropriate. If you encounter any such thing in the English version, then please open an issue here. But I assure you those weren’t intentional. And in translation repos, those might be just mistranslations.
