### ISSUE TITLE
the search function of the online page is not worked

### ISSUE THREAD

**Issue by jiechen257** [vuejs/docs#2823]
Clicking the search button or cmd + k does not trigger the search box to appear

**Comment by wuguichiroumeiyou** [comment]
It worked via a proxy, but there may still be something wrong with the website deployment.
<br>
![image](https://github.com/vuejs/docs/assets/26672927/1b18e5ab-56f7-4514-bfad-897808de23a9)
These are the 404 errors I encountered when directly visiting the Chinese-simplified translation URL from China without using a proxy. This could be the reason for all kinds of function disabilities. I also tried other language translation URLs at the same time, and they worked just fine with no errors in the console.

**Comment by brc-dd** [comment]
Like I said there is nothing wrong with the deployment

<img width="437" alt="image" src="https://github.com/vuejs/docs/assets/40380293/5671593f-c1f8-4b38-82af-77b237362105">

\
The issue is we can't host anything inside China. And external hosts like Vercel get frequently blocked there. It's a common issue, but unfortunately we don't have a perfect solution. The other translation sites are using Netlify, but that too used to break frequently in China.
