### ISSUE TITLE
v-model parameters are different in Playground and web，makes it difficult to understand

### ISSUE THREAD

**Issue by POKEZHANG** [vuejs/docs#2843]
Website：https://play.vuejs.org/#eNqFkl9PwjAUxb9K05dhglsMb2SQqOFBE9Soj31Zxh0Uu7bpHxxZ9t29LWOiQXzaes7p2a+9a+mt1unOA53S3JaGa0csOK/nTPJaK+NISwxUpCOVUTVJMJoM1nJ/r/BNgnS9nWYnWujFMCFMlkpaRxx3AsgsFI6S3XWtViBIYda+Dg3QFLUWkFwxmWcHFqTAhQPUCwe4IiTf3Mzbtq/qujzDddRPYfruaUzNGI1PRkmG0Twb+uiY/sI9cw0/0VdQcQnL0D5KovgfL5fa4/69jiDQOOTo+S6SOYtfrvg63VolkauNN0lLxOUCzLN2HMkYnZLoBK8QQn0+Rs0ZD+OjXm6g/Dijb20TNEZfDFgwOwQZPIdzAWQN9uLtKXIPJtL7gH3BfAWrhA+Mh9idlyvEPslF2of4J3G5freLxoG0x0MF0JDsYp5RHE6Y1F9H/8adpJO4j8mOdl/Hw/nf
Pic：
![2024-04-30T10_06_56](https://github.com/vuejs/docs/assets/31927941/1eaabd3d-65bd-482e-a79e-39a0c440dc83)

**Comment by xiaodong2008** [comment]
It's not hard to understand, just different names of variables.

For docs: it's good to use `title` and `bookTitle` separately to distinguish between father and child components.
For playground: it's clear because you can switch between two components and this shouldn't change to `bookTitle` because it doesn't match the playground demo

**Comment by NataliaTepluhina** [comment]
I've fixed the playground to match the docs chapter 👍🏻
