### ISSUE TITLE
vue中文版文档刷新页面有js报错

### ISSUE THREAD

**Issue by Tangchen2016** [vuejs/docs#2880]
访问地址：https://cn.vuejs.org/api/sfc-script-setup.html#defineprops-defineemits
浏览器：Chrome 124.0.6367.209

![image](https://github.com/vuejs/docs/assets/18592893/c585adf7-a8ae-4e81-aa7c-1519f101d961)

**Comment by xiaodong2008** [comment]
This is because the page failed to request some file(s).

That is not a problem related to [vuejs/docs](https://github.com/vuejs/docs), please go to [vuejs-translations/docs-zh-cn](https://github.com/vuejs-translations/docs-zh-cn), but I think [this](https://github.com/vuejs-translations/docs-zh-cn/issues/919#issuecomment-2087945070) can answer your question.
