### ISSUE TITLE
Add a note or caution to the documentation for the `customRef` function.

### ISSUE THREAD

**Issue by demershov** [vuejs/docs#2884]
I encountered an issue with the `customRef` function, where it wasn't working as i expected.
First of all, I would like to note that I have already discussed this issue with @LinusBorg and @skirtles-code in the community chat. I've come to the conclusion that although this is the expected behavior for `customRef`, it would be beneficial to add additional information to the documentation for other developers like me.

If a `get()` method inside the `customRef` returns an object that is the same as the previous value but is newly generated, then components that accept this `customRef` as a prop will perceive the new object as modified value. It is important to note that the trigger will not happen inside the `set()` method.

Steps to reproduce:
1. Declare a variable using the `customRef` in a parent component.
2. Pass this variable as prop for the child component.
3. Change another sibling component in the parent component that is not associated with this variable.
4. The parent component is re-rendered, but since the variable declared using `customRef` is tracks by the parent component render effect, the `get()` in the `customRef` is called again, and the getter, in turn, returns a new object but with the same shape.
5. For the child component, this will be a new object and the child component will be re-rendered, even though the props haven't been explicitly changed. 
6. If will add a watcher for this variable inside the parent component, then the watcher will not trigger a callback, because the `trigger` function was not called inside a `set()` of the `customRef`.

Link to the [Playground](https://play.vuejs.org/#eNqFVEtP3DAQ/itTS9Vm1ZCt1J6WBZUiDvTQIsoNcwiOkzU4tmU7+9Aq/71jO1mCWuhlN/PyfPP45kAujCk2HSdLsnLMCuPBcd+Zc6pEa7T1cADWOa/bW17nYMPPtvRsDT3UVrcww+DZ0flStybpKSkWQQqPU0IVVUwr58FYvdvDWXgpu6ek1pqSHL0fS0vJw/z0xbN1jUPHY/Ys87Zkzzl4K5qG2zmcnUN2oAqg4T6bQ/wENKNXNk+CxWKsSlmLTSk7XlhedYxnWclYDiK+MkQCoK4wnVtnIiBJuuEJNA2qPof7hzkEoc8DXgg9yzYTBBFgNr4xyY4FbaK2p6qfI0iqFgtgulOe27HyQRy69Dk1JXY9C03JIeQ6wg4xWvJCqFpnlNytOcyC2wzYulQNr0Ao+Mhw0KnTTEttl/CIaIJiMz8NGBHFtYetVrPwa58/IL48Zag4N0ssquNYLYBoW16J0vOkC3VQtVqk7cG9QcHz1kj0QAlgVYkNMFk6d0bJ1pbGYKUkmtD42HmvFfi94WhOEiXwjUnBnlEz9OLTJwy5qCo44D4O7en71SIFjI/F9VuG4jEy/GHQKq5hQrJAKOc4uNVighBF5/cygS0GgOMoK+HQb7+EWvLdMM7weVIJy5kXWi0Rj+xaNRhLKRp1IvB9hxYegA6WJ1xkUe9PcF4e9a+suA3YwYiC5MQ79KlFUzw5rZCZEUtoRWuE5PaXCXmxtuWIkpJSSr39EXXHQcWYNWfP/9A/uV3QUXJjueN2E1ZhtPnSIqGS+er3T77D76Ox1VUn0fsd4y3HfewCxuT2vVMVwp74RbTX8WQI1dy5qx12xI1Fpa1K5AreeEHCCN8q/QXul+LrSC3s4nh93jltkVPDIYt5KJkcIKStCReo4rVQ/CZI6dyEzToCCJu7hAtry/1QH/qXncQB400KJwqPxZHxEyona0xS/E3rt1m9Ld1rZl+uhaxecRtP3EjtgddCyimtXyj9H/Ii3eId7uOGTkyk/wOEbQ9h)

I've also created an issue at https://github.com/vueuse/vueuse/issues/3992 as the `useRouteQuery` also suffers from this behavior.

Thanks.

**Comment by seeniOlabode** [comment]
Hello, thank you for logging this.

I have tested this in the Playground and confirmed the unexpected behavior. Here’s a breakdown of what happens:

- Change Unrelated State: An unrelated state change in the parent component triggers its render function.
- Component Re-render: This causes the parent component to re-render, which includes re-evaluating Comp.vue.
- Evaluate CustomRef: The customRef's get() method is called again, returning a new object with the same structure as the previous value.
- Prop Comparison: During re-rendering, Vue compares the new and previous props of the child component.
- Perceived Prop Change: Although the objects are structurally identical, they are different instances. Vue perceives this as a prop change.
- Child Component Re-render: This perceived prop change triggers the child component to re-render and its watchers to react, despite no actual change in the logical state.
- This behavior occurs because the customRef does not trigger updates inside its set() method, leading to reactivity issues when the getter returns a new object instance.

Let me know if this is the case per your deductions.

**Comment by demershov** [comment]
Hello @seeniOlabode 
Yes, it seems that this is the case. 

If you or somebody take a closer look, will understand why this happens. However, I believe it would be beneficial to include this information in the documentation.
