### ISSUE TITLE
"state.count = otherCount" should be "state.count = otherCount.value"

### ISSUE THREAD

**Issue by vcc0827** [vuejs/docs#3013]
In this case，i think 'otherCount' should be 'otherCount.value'.

const otherCount = ref(2)

state.count = otherCount
console.log(state.count) // 2
console.log(count.value) // 1
locate in https://v3.vuejs.org/guide/reactivity-fundamentals.html#ref-unwrapping

I followed this tutorial and got an unexpected result。
<img width="1028" alt="vue3ref-issue" src="https://github.com/user-attachments/assets/b7097966-5513-409a-8135-991b6fc8bcc4">

but if i use otherCount.value to replace it, i can get the right answer. 
can anybody tell me why?

**Comment by AloisSeckar** [comment]
In the code example just above the one you mentioned, `state.count` is defined like this:
```
const count = ref(0)
const state = reactive({
  count
})
```
So `state.count` is of type `Ref<number>`.

If we say we want to "replace it", we have to use the same type - thus the whole `otherCount` object, which is also `Ref<number>`. Type of `otherCount.value` is just a `number`, so completely different thing. TypeScript will yell at you because of type mismatch. JavaScript would allow it, but you'd lose the ability of future reactive updates on `state.count`.

Also, note this example is not meant to be "right" or "wrong". It is designed just to show what will happen in the improbable case you would like to replace a ref inside a reactive object.

**Comment by vcc0827** [comment]
Thank you for your answer! I can understand the meaning that this example is trying to convey now。
May you have a nice day~
