### ISSUE TITLE
Vue 3 migration guide link doesn't mention any proper migration way from vue 2 to vue 3

### ISSUE THREAD

**Issue by RitikPatni** [vuejs/docs#505]
The migration link on the vue-next Readme page links to this [page](https://v3.vuejs.org/guide/migration/introduction.html) and I expected that page to contain steps related to migrating from Vue 2 to Vue 3 but the [page](https://v3.vuejs.org/guide/migration/introduction.html) mentions breaking changes and how to create a new Vue 3 App but there is nothing which remotely suggests it as a migration guide.

Please provide a link to the migration guide if it already exists or please suggestive alternative migration guide to follow in order to migrate from Vue 2 to Vue 3

**Comment by LinusBorg** [comment]
Could you go into a bit more detail what kind of information you are missing? 

The one thing we already realized and were already discussing today is that there is no guidance about how to update your dependencies in order to make your app ready for a Vue 3. We are working on that as I write this. However, as there are lots of ways to include Vue into different kinds of projects for example using "laravel-mix" in a Laravel application, we can only provide general guidance in that regard. 

We must trust that the community and projects like Laravel provide similar guidance for their specific use cases and tool chains.

Apart from that, what you referred to as "mentions of breaking changes ", are in fact deep dives into each of the changes - including migration strategies for each of them. So you can work through these and adjust your code with the recommended migration strategy.

Is there anything missing in these feature-by-feature migration guides or what kind of strategies or guidance are you missing beyond what I already mentioned above?

Also note that in the release notes and announcement for review 3.0 we mention that we are still working on a specific migration build that comes with deprecation warnings, As well as code my script that can transform parts of your coat that are automatically migrateable If you are looking for something like this, please hold out a little longer.

**Comment by RitikPatni** [comment]
@LinusBorg Thanks for the quick revert. So what I was expecting from Vue 3 migration guide was some sort of command or some set of steps that will help me migrate from Vue 2 to Vue 3.

The breaking changes are surely helpful but there is nothing after that like how will I bump the package numbers after making all the changes. I was expecting more clarity and help on how should I start with breaking changes and once those are done there should be a simple npm command or cli command which will smoothly migrate to Vue 3 without any hassle.

**Comment by LinusBorg** [comment]
As mentioned, we are working on providing more guidance concerning updating of packages. That should be available pretty soon. For more automated support of migration as mentioned above please wait for the migration build and migration tool which is being worked on in the next quarter.

**Comment by RitikPatni** [comment]
@LinusBorg Thanks I'll wait for more clarity on that in the meantime can you refer me to any beta docs or what to do after making the breaking changes if it won't take much of your time

**Comment by garygreen** [comment]
I too find the current "migration guide" to be a little unhelpful. The first steps of the migration guide are detailing steps on how to *scaffold a new project* which is completely irrevelate to a *migration guide* where you want to update an existing app.

There is also an overwhelming amount of links to seperate pages which adds a bit of friction to the upgrade process, as you have to click through to each page to work out if it affects you.

So for me, I think a number of improvements can be made:

* **Detail how to upgrade your npm packages** (as you mentioned, this could be tricky to do as theres a lot of ways to include Vue, e.g. with Laravel Mix etc, but in general I think having a guide for Vanilla, Webpack and Parcel would satisfy most users.

* **A simple list of common before and after code examples** of what syntaxally has changed. Again, could be tricky due to the vast API and ways Vue could be used, but the main thing is the guide should cater for the most common scenarioes.

* **Keep as much information on one page as possible, with a summary at the top** - reduces friction in having to click through to many different links to see full code examples. Lesser, more obscure ways of using Vue can be added as seperate links to a different page.

Laravel is a good example of how to do a migration guide well. See here: https://laravel.com/docs/5.8/upgrade - it gives you a summary of the changes, how likely they are to affect you, estimated time to upgrade, etc. It's all contained on one page without having to jump between loads of pages.

**Comment by EmielSchmeink** [comment]
Is there an ETA on when this migration guide will be live?

**Comment by huymichael** [comment]
Any guide for migrate vue 2 to vue 3 step by step for now? I can't find the best guideline to upgrade vue project ver 2 to 3
 I see angular have a good doc for migration https://update.angular.io/?v=10.0-11.0

**Comment by ErikWahlstrom** [comment]
Awfully quite here...

Is there any ETA on the migration build mentioned. Would be really nice to know if it's worth waiting for.

https://v3.vuejs.org/guide/migration/introduction.html#breaking-changes

**Comment by Alanscut** [comment]
Hi @LinusBorg , any progress on the migration build mentioned? Is the form of the tool capable of completely automatically converting a vue2 project to a vue3 project, or is it something like [vue-migration-helper](https://github.com/vuejs/vue-migration-helper) that provides detailed warnings when deprecated patterns are found?  If this project is in progress, is it possible to open source the code?

**Comment by NataliaTepluhina** [comment]
@Alanscut still in progress, no ETA so far.

**Comment by zleight1** [comment]
Since this is a little behind the original estimated schedule, is there any thought to extending Vue 2 support timeline?

This is because many of us will need this build to migrate from 2 to 3, so delays on this build delays our overall upgrade timeline as well.

**Comment by NataliaTepluhina** [comment]
@zleight1 while I agree with your point, I don't think this discussion can be resolved within the scope of the documentation (where this issue belongs). The team is actively working on compatibility build to improve a migration experience, and as soon as it's ready to be public, we will add this to the documentation.

**Comment by NataliaTepluhina** [comment]
Closing an issue as we have 3.1 migration build with the instruction now: https://v3.vuejs.org/guide/migration/introduction.html#migration-build
