### ISSUE TITLE
Custom directives missing expression

### ISSUE THREAD

**Issue by 0x1af2aec8f957** [vuejs/docs#758]
In the binding object passed to the parameter of directive hooks, there is an expression of 'expression' in version 2.x. by parsing this parameter, the variable assignment of the instruction can be changed. If there is no such parameter in version 3. x, how can I change it?

The binding parameter in 2.x contains the expression field.How do I get expressions in 3.x?

**Comment by palant** [comment]
I noticed the same issue. It seems that `binding.expression` is gone in Vue 3, presumably to avoid the ambiguity here – the value is always evaluated, so you only have `binding.value` which is the evaluated expression result. I’d say that you need to use directive argument if you don’t want evaluation, it will be available in `binding.arg`. So `v-directive:foo` rather than `v-directive="foo"`.

This needs better documentation IMHO. This change isn’t mentioned in the migration guide from what I can tell. Also, https://v3.vuejs.org/guide/custom-directive.html is missing the overview of parameters and their properties which was present in the previous version – https://vuejs.org/v2/guide/custom-directive.html#Directive-Hook-Arguments.

**Comment by LinusBorg** [comment]
the parameters and their properties are explained in the API docs and link to from the guide in this paragraph:

> You can check the arguments passed into these hooks (i.e. el, binding, vnode, and prevVnode) in [Custom Directive API](#)

..though the fact that you missed it is reason enough to consider re-introducting this listing in the guide itself.

**Comment by palant** [comment]
Heh, I actually looked at the API reference first but didn’t realize that I need to look at `application.directive()`…
